"""initial schema

Revision ID: f1a13823b537
Revises: 
Create Date: 2026-08-15 19:17:37.461343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a13823b537'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index('ix_agent_jobs_status_created', 'agent_jobs', ['status', 'created_at'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('schedule', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=False),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('azure_sync_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('upserted', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('defects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('azure_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('iteration_id', sa.BigInteger(), nullable=True),
    sa.Column('iteration_name', sa.String(length=255), nullable=False),
    sa.Column('story_work_item_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('is_escaped', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azure_id')
    )
    op.create_index('ix_defects_severity', 'defects', ['severity'], unique=False)
    op.create_index('ix_defects_state', 'defects', ['state'], unique=False)
    op.create_index('ix_defects_story_work_item_id', 'defects', ['story_work_item_id'], unique=False)
    op.create_table('iterations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('azure_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azure_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dedup_key', sa.String(length=255), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pull_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('azure_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('target_ref', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azure_id')
    )
    op.create_table('report_archives',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('sprint_name', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('html_path', sa.String(length=512), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('suggested_framework', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_test_cases_status', 'test_cases', ['status'], unique=False)
    op.create_table('test_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('flaky', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('report_location', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_test_runs_created_at', 'test_runs', ['created_at'], unique=False)
    op.create_table('test_implementations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_case_id', sa.BigInteger(), nullable=False),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'framework', 'path', name='uq_impl_framework_path')
    )
    op.create_table('test_scenarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_case_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_items',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('azure_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria_raw', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=False),
    sa.Column('iteration_id', sa.BigInteger(), nullable=True),
    sa.Column('iteration_name', sa.String(length=255), nullable=False),
    sa.Column('area_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('parent_azure_id', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['iteration_id'], ['iterations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azure_id')
    )
    op.create_index('ix_work_items_iteration_id', 'work_items', ['iteration_id'], unique=False)
    op.create_index('ix_work_items_state', 'work_items', ['state'], unique=False)
    op.create_index('ix_work_items_type', 'work_items', ['type'], unique=False)
    op.create_table('acceptance_criteria',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('work_item_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'sort_order', name='uq_ac_workitem_order')
    )
    op.create_table('azure_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('work_item_id', sa.BigInteger(), nullable=False),
    sa.Column('azure_comment_id', sa.BigInteger(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('azure_comment_id')
    )
    op.create_table('test_matrix_analyses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('work_item_id', sa.BigInteger(), nullable=False),
    sa.Column('coverage_pct', sa.Float(), nullable=False),
    sa.Column('missing_ac_count', sa.Integer(), nullable=False),
    sa.Column('existing_tests_reused', sa.Integer(), nullable=False),
    sa.Column('new_tests_required', sa.Integer(), nullable=False),
    sa.Column('potentially_redundant_tests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_new_functionality', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_work_item_generated', 'test_matrix_analyses', ['work_item_id', 'generated_at'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_run_id', sa.BigInteger(), nullable=False),
    sa.Column('implementation_id', sa.BigInteger(), nullable=True),
    sa.Column('test_case_id', sa.BigInteger(), nullable=True),
    sa.Column('scenario_id', sa.BigInteger(), nullable=True),
    sa.Column('framework', sa.String(length=32), nullable=False),
    sa.Column('suite', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=128), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('is_flaky', sa.Boolean(), nullable=False),
    sa.CheckConstraint("status IN ('PASSED','FAILED','SKIPPED','BLOCKED','FLAKY','ERROR')", name='ck_test_result_status'),
    sa.ForeignKeyConstraint(['implementation_id'], ['test_implementations.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['test_scenarios.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_run_id'], ['test_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_results_started_at', 'test_results', ['started_at'], unique=False)
    op.create_index('ix_test_results_status', 'test_results', ['status'], unique=False)
    op.create_index('ix_test_results_test_case_id', 'test_results', ['test_case_id'], unique=False)
    op.create_table('test_defect_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('defect_id', sa.BigInteger(), nullable=False),
    sa.Column('test_result_id', sa.BigInteger(), nullable=True),
    sa.Column('test_case_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('linked_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_generation_candidates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('work_item_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('acceptance_criterion_id', sa.BigInteger(), nullable=True),
    sa.Column('framework', sa.String(length=16), nullable=False),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=False),
    sa.Column('generated_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['test_matrix_analyses.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_story_links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('work_item_id', sa.BigInteger(), nullable=False),
    sa.Column('acceptance_criterion_id', sa.BigInteger(), nullable=True),
    sa.Column('test_case_id', sa.BigInteger(), nullable=False),
    sa.Column('coverage_status', sa.String(length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acceptance_criterion_id'], ['acceptance_criteria.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'acceptance_criterion_id', 'test_case_id', name='uq_storylink')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_story_links')
    op.drop_table('test_generation_candidates')
    op.drop_table('test_defect_links')
    op.drop_index('ix_test_results_test_case_id', table_name='test_results')
    op.drop_index('ix_test_results_status', table_name='test_results')
    op.drop_index('ix_test_results_started_at', table_name='test_results')
    op.drop_table('test_results')
    op.drop_index('ix_analysis_work_item_generated', table_name='test_matrix_analyses')
    op.drop_table('test_matrix_analyses')
    op.drop_table('azure_comments')
    op.drop_table('acceptance_criteria')
    op.drop_index('ix_work_items_type', table_name='work_items')
    op.drop_index('ix_work_items_state', table_name='work_items')
    op.drop_index('ix_work_items_iteration_id', table_name='work_items')
    op.drop_table('work_items')
    op.drop_table('test_scenarios')
    op.drop_table('test_implementations')
    op.drop_index('ix_test_runs_created_at', table_name='test_runs')
    op.drop_table('test_runs')
    op.drop_index('ix_test_cases_status', table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_table('report_archives')
    op.drop_table('pull_requests')
    op.drop_table('notifications')
    op.drop_table('iterations')
    op.drop_index('ix_defects_story_work_item_id', table_name='defects')
    op.drop_index('ix_defects_state', table_name='defects')
    op.drop_index('ix_defects_severity', table_name='defects')
    op.drop_table('defects')
    op.drop_table('azure_sync_logs')
    op.drop_table('agents')
    op.drop_index('ix_agent_jobs_status_created', table_name='agent_jobs')
    op.drop_table('agent_jobs')
    # ### end Alembic commands ###
