"""Application configuration loaded from environment variables."""
from __future__ import annotations

from functools import lru_cache
from typing import Literal

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env", env_file_encoding="utf-8", extra="ignore", case_sensitive=False
    )

    # --- app ---
    app_name: str = "UAT Test Management Intelligence Platform"
    app_env: Literal["development", "demo", "production"] = "development"
    api_prefix: str = "/api/v1"
    api_token: str = ""
    log_level: str = "INFO"
    log_format: Literal["json", "text"] = "json"
    root_path: str = ""

    # --- database ---
    database_url: str = (
        "postgresql+psycopg2://uat:uat@db:5432/uat_test_intelligence"
    )

    # --- azure devops ---
    azure_devops_org: str = ""
    azure_devops_project: str = ""
    azure_devops_pat: str = ""
    azure_devops_api_version: str = "7.1"
    azure_comment_on_analysis: bool = False
    azure_git_repo_name: str = ""
    azure_git_remote_url: str = ""

    # --- llm ---
    llm_provider: str = "none"
    llm_model: str = ""
    llm_api_key: str = ""
    llm_base_url: str = ""
    llm_timeout_seconds: float = 60.0
    llm_max_retries: int = 1

    # --- notifications ---
    notifications_enabled: bool = True
    notification_provider: str = "log"
    telegram_enabled: bool = False
    telegram_bot_token: str = ""
    telegram_chat_id: str = ""
    email_enabled: bool = False
    email_host: str = ""
    email_port: int = 587
    email_username: str = ""
    email_password: str = ""
    email_from: str = "uat-platform@example.com"
    whatsapp_enabled: bool = False
    whatsapp_api_url: str = ""
    whatsapp_api_token: str = ""
    webhook_enabled: bool = False
    webhook_url: str = ""
    webhook_token: str = ""

    # --- reporting ---
    report_company_name: str = "Acme Corp"
    report_logo_path: str = ""
    report_primary_color: str = "#0f4c81"
    report_secondary_color: str = "#6c757d"
    report_footer: str = "Confidential - generated by UAT Test Intelligence Platform"
    report_engine: str = "weasyprint"
    report_templates_dir: str = ""

    # --- scheduling ---
    schedule_azure_sync: str = "*/10 * * * *"
    schedule_test_execution: str = "*/30 * * * *"
    schedule_report_generation: str = "0 15 * * 5"
    schedule_nightly_regression: str = "0 2 * * *"
    agents_enabled: bool = True

    # --- storage ---
    storage_backend: str = "local"
    storage_local_root: str = "/data"
    reports_root: str = "/data/reports"

    # --- runner configuration ---
    api_runner_url: str = "http://api-tests:5001"
    web_runner_url: str = "http://web-tests:6000"
    demo: bool = False

    # --- demo product ---
    demo_weather_api_url: str = "http://weather:5000"
    demo_webapp_url: str = "http://webapp:8000"

    # --- jobs ---
    job_default_timeout_seconds: int = 300
    job_worker_concurrency: int = 4

    @property
    def is_demo(self) -> bool:
        return self.app_env in {"demo", "development"}


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
